plot1:
    number_plots: one
    plot_name: p1_one_set_multiple_runs_timeseries.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot2:
    number_plots: one
    plot_name: p2_one_set_multiple_runs_ts_quantile.png
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None
    fill_between_quartiles: yes
    fillcolor: red

plot3:
    number_plots: one
    plot_name: p3_ts_multibatch_analysis.png
    plot_legend: yes
    legend_location: best
    x-axis label: Time
    y-axis label: price
    linestyle: solid
    marker: None
    fill_between_quartiles: yes
    fillcolor: darkgreen

plot4:
   number_plots: one
   plot_name: p4_one_set_one_run_agentanalysis_timeseries.png
   plot_legend: no
   legend_location: best
   xaxis_label: Time
   yaxis_label: price
   linestyle: solid
   marker: None

plot5:
    number_plots: one
    plot_name: p5_one_set_one_run_bp_price.png
    plot_legend: yes
    legend_label: (Agent = Firm, var = Price)
    legend_location: best
    xaxis_label: Time
    yaxis_label: Distribution over price
    number_bars: 5

plot6:
    number_plots: one
    plot_name: p6_one_set_multiple_runs_sp_price_output.png
    plot_legend: yes
    legend_location: best
    legend_label: price vs. output
    linestyle: solid
    marker: +

plot7:
    number_plots: one
    plot_name: p7_one_set_agent_sp_price_delay.png
    plot_legend: no
    legend_location: best
    legend_label: price delay vs. price
    marker: +

plot8:
    number_plots: one
    plot_name: p8_one_set_multiple_runs_sp_price_delay.png
    plot_legend: yes
    legend_location: best
    legend_label: price delay vs. price
    linestyle: solid
    marker: o

plot9:
    number_plots: one
    plot_name: p9_one_set_one_run_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot10:
    number_plots: one
    plot_name: p10_one_set_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot11:
    number_plots: one
    plot_name: p11_one_set_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot12:
    number_plots: one
    plot_name: p12_two_sets_multiple_runs_hg_price.png
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: step
    plot_legend: yes
    fill: no
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel
