timeseries:
    agent: 'Bank'
    analysis: 'parameter'    
    variables: ['total_credit','excess_liquidity']
    set: [1]
    run: [1,2]
    major: [range,[6020,6100,20]]
    minor: [range,[1,10]] 
    plot properties:
        number_plots: 'single'
        plot_label: 'no'

boxplot:
    agent: 'Eurostat'
    analysis: 'agent' 
    variables: 'monthly_output'
    set: [1]
    run: [range,[1,2]]
    major: [range,[6020,6100,20]]
    minor: [1,5,7,12] 
    plot properties:
        number_plots: 'multiple'
        plot_label: 'yes'
