plot1:
    number_plots: one
    plot_legend: yes
    #plot_name: p1_set_own_name
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None

plot2:
    number_plots: one
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None
    fill_between: no
    fillcolor: red

plot3:
    number_plots: one
    plot_legend: yes
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None
    fill_between: yes
    fillcolor: darkgreen

plot4:
    number_plots: one
    plot_format: png
    plot_legend: no
    legend_location: best
    xaxis_label: Time
    yaxis_label: price
    linestyle: solid
    marker: None
    greyscale: True

plot5:
    number_plots: one
    plot_legend: yes
    legend_label: (Agent = Firm, var = Price)
    legend_location: best
    xaxis_label: Time
    yaxis_label: Distribution over price
    number_bars: 5
    greyscale: False

plot6:
    number_plots: one
    plot_legend: yes
    legend_location: best
    legend_label: price vs. output
    linestyle: solid
    marker: +

plot7:
    number_plots: one
    plot_legend: no
    legend_location: best
    legend_label: price delay vs. price
    marker: +

plot8:
    number_plots: one
    plot_legend: yes
    legend_location: best
    legend_label: price delay vs. price
    linestyle: solid
    marker: o

plot9:
    number_plots: one
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill_between: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot10:
    number_plots: one
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill_between: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot11:
    number_plots: one
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: bar
    plot_legend: yes
    fill_between: yes
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel

plot12:
    number_plots: one
    plot_title: (Agent = Firm, var = Price)
    number_bins: 50
    histtype: step
    plot_legend: yes
    fill_between: no
    stacked: False
    legend_location: best
    xaxis_label: xlabel
    yaxis_label: ylabel
