i/o:
    input_path: '/home/susupta/Desktop/GitHub/Bank'

    input_files:
        Bank: Bank.h5  # please name the key as the agent name
        Eurostat: Eurostat.h5

    output_path: '/home/susupta/Desktop/Fix_preprocess/visualize/src/output'

plot1:
    timeseries:
        agent: Bank
#        analysis: multiple_set
        analysis: agent
        variables: 
#              var1: [total_credit, '>[700]', '<[800]']
            var1: [total_credit]  
#              var2: [equity]     
            var2: [equity, '>[900]']
        set: [1]
        run: [1,2]
        major: [range,[6020,26000,20]]
        minor: [1,5,7] 
        summary: custom_quantile
        quantile_values:          
            lower_quantile : 0.50
            upper_quantile : 0.90
        

#plot2:
#    transform:
#        agent: Bank
#        analysis: multiple_set
#        variables: 
#            var1: [total_credit]       
#        set: [1]
#        run: [1]
#        major: [range,[6020,6300,20]]
#        minor: [1,5] 
#        summary: mean
#        conditional_filtering:
#            yes/no: no
            

#plot3:
#    scatterplot:
#        agent: Bank
#        analysis: multiple_batch
#        variables: 
##            var1: [total_credit, '>[700]', '<[800]']
#            var1: [total_credit]       
##            var2: [equity, '>[900]']
#        set: [1]
#        run: [1,2]
#        major: [range,[6020,26000,20]]
#        minor: [1,5,7] 
#        summary: custom_quantile
#        conditional_filtering:
#            yes/no: yes
#            condition_var: [total_credit, '>[700]']
#            operation_var: [total_credit, '>[700]', '<[800]']


#plot3:
#    histogram:
#        agent: Bank
#        analysis: multiple_batch
#        variables: 
##            var1: [total_credit, '>[700]', '<[800]']
#            var1: [total_credit]       
##            var2: [equity, '>[900]']
#        set: [1]
#        run: [1,2]
#        major: [range,[6020,26000,20]]
#        minor: [1,5,7] 
#        summary: mean
#       conditional_filtering:
#            yes/no: yes
#            condition_var: [total_credit, '>[700]']
#            operation_var: [total_credit, '>[700]', '<[800]']



#plot4:
#    timeseries:
#        agent: Bank
#        analysis: agent
#        variables: 
#            var1: [total_credit]       
#        set: [1]
#        run: [1,2]
#        major: [range,[6020,6100,20]]
#        minor: [range,[1,2]] 
#        summary: mean
#        conditional_filtering:
#            yes/no: no
        

#plot5:
#    boxplot:
#        agent: Bank
#        analysis: multiple_set
#        variables:      
#            var1: [total_credit]                          
#        set: [1]
#        run: [range,[1,2]]
#        major: [range,[6020,26000,20]]
#        minor: [1,5,7]
#        conditional_filtering:
#            yes/no: no 

