
plot2:
    variables: 
        var1: total_credit
        var2: total_credit        
    transform_function: m_o_m_ONE_CYCLE
    aggregate: mean    
 
    write_file: yes
    output_path: '/home/susupta/Desktop/GitHub/ETACE/TODO/visualisation/transform_out/outsent.h5'
    hdf_groupname: 'total_credit_ratio'   
    

