timeseries:
    agent: 'Bank'
    analysis: 'multiple_batch'
    variables: ['total_credit']
    set: [1,2]
    run: [1,2,3,4,5,6]
    major: [range,[6020,26000,20]]
    minor: [range,1] 
    summary: 'mean'
    plot properties:
        number_plots: 'one'
        plot_label: 'no'

boxplot:
    agent: 'Bank'
    analysis: 'multiple_set' 
    variables: 'total_credit'
    set: [1]
    run: [range,[1,3]]
    major: [range,[6020,26020,20]]
    minor: [1,5,7] 
    plot properties:
        number_plots: 'one'
        plot_label: 'yes'


histogram:
    agent: 'Bank'
    analysis: 'multiple_set'    
    variables: ['total_credit']
    set: [1]
    run: [1,2]
    major: [range,[6020,26020,20]]
    minor: [range,[1,5]] 
    summary: 'mean'    
    plot properties:
        number_plots: 'one'  #multiple, not fixed yet
        plot_label: 'no'
