i/o:
    input_path: '/home/susupta/Spaces/ETACE-Conquaire Project/Data/data_reproduction_task/timeseries_classify_LS_input'

    output_path: '/home/susupta/Spaces/ETACE-Conquaire Project/Data/data_reproduction_task/timeseries_classify_LS_output'

plot1:
    timeseries:
        agent: Bank
        analysis: agent
        variables: 
#            var1: [total_credit, '>[700]', '==[731.537383]']
            var1: [total_credit]       
#            var2: [equity, '>[900]']
        set: [1]
        run: [1,2]
        major: [range,[6020,26000,20]]
        minor: [range,[1,2]] 
        summary: mean
        plot properties:
            number_plots: one
            plot_label: no


plot2:
    timeseries:
        agent: Bank
        analysis: agent
        variables: 
            var1: [total_credit]       
        set: [1]
        run: [1,2]
        major: [range,[6020,26000,20]]
        minor: [range,[1,2]] 
        summary: mean
        plot properties:
            number_plots: one
            plot_label: no


#plot2:
#    boxplot:
#        agent: Eurostat
#        analysis: multiple_set
#        variables:      
#            var1: [total_credit]                          
#        set: [1]
#        run: [range,[1,3]]
#        major: [range,[6020,6100,20]]
#        minor: [1,5,7] 
#        plot properties:
#            number_plots: one
#            plot_label: yes
