plot1:
    number_plots: one
    plot_name: timeseries_agentanalysis.png
    plot_legend: yes
    legend_location: best
    legend_label: total_credit
    x-axis label: some x label
    y-axis label: some y label
    linestyle: solid
    marker: o
    markerfacecolor: green
    markersize: 1
        



plot2:
    number_plots: one
    plot_name: second_one.png
    l_lim: no
    u_lim: no
    tmin: no
    tmax: no
    plot_legend: no
    legend_loc: out
    legend_label: second_option
    x-axis label: not yet done
    y-axis label: some y label
    linestyle: solid

plot3:
    number_plots: one
    plot_name: third_one.png
    l_lim: no
    u_lim: no
    tmin: no
    tmax: no
    plot_legend: no
    legend_loc: out
    legend_label: third_option
    x-axis label: not yet done
    y-axis label: some y label
    linestyle: solid

plot5:
    number_plots: one
    plot_name: sum_one.png
