plot1:
    plot_type: timeseries
    variables: total_credit
    number_plots: one
    plot_name: summary.png
    l_lim: no
    u_lim: no
    tmin: no
    tmax: no
    plot_legend: yes
    legend_loc: out
    x-axis label: some x label
    y-axis label: some y label
    

