plot1:
    plot_type: timeseries
    variables: total_credit
    number_plots: many
    plot_name: first_one.png
    l_lim: no
    u_lim: no
    tmin: no
    tmax: no
    plot_legend: yes
    legend_loc: out
    legend_label: total credit
    x-axis label: some x label
    y-axis label: some y label
    linestyle: dashed
    

plot2:
    plot_type: timeseries
    variables: total_credit
    number_plots: one
    plot_name: second_one.png
    l_lim: no
    u_lim: no
    tmin: no
    tmax: no
    plot_legend: no
    legend_loc: out
    x-axis label: some x label
    y-axis label: some y label

